/**
 * --------------------------------------------------------------------
 * docmd-search : offline semantic search for docs, zero-config.
 *
 * @package     docmd-search (and ecosystem)
 * @website     https://docmd.io/search
 * @repository  https://github.com/docmd-io/docmd-search
 * @license     MIT
 * @copyright   Copyright (c) 2026-present docmd.io
 *
 * [docmd-source] - Please do not remove this header.
 * --------------------------------------------------------------------
 */

/**
 * Web UI launcher via docmd.
 *
 * docmd-search and docmd are completely independent tools.  When the user
 * runs `docmd-search ./docs --ui`, docmd-search:
 *
 *   1. Indexes the directory (builds .docmd-search/ batches) — its own job.
 *   2. Writes a self-contained docmd.config.json into .docmd-search/_ui/.
 *   3. Spawns `npx @docmd/core dev` pointed at that config.
 *
 * The generated config tells docmd to use its own plugin-search with
 * `semantic: true` AND an `indexDir` pointing at the already-built index.
 * This way docmd's plugin-search skips re-indexing entirely — it just reads
 * the batches that docmd-search already produced and serves the semantic
 * client bundle.  No dependency loop: docmd doesn't call back into
 * docmd-search; it just reads files from disk.
 *
 * If docmd is not installed, the error message tells the user how to install
 * it.  docmd is an *optional* runtime dep for --ui mode only.
 */

import { writeFile, mkdir, copyFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { spawn, execFileSync } from 'node:child_process';

/* ── ANSI ──────────────────────────────────────────────────── */

const A = {
  reset: '\x1b[0m',
  bold:  '\x1b[1m',
  dim:   '\x1b[2m',
  magenta: '\x1b[35m',
  green: '\x1b[32m',
  red:   '\x1b[31m',
  yellow:'\x1b[33m',
};

/* ── Config Generation ─────────────────────────────────────── */

/**
 * Generate a docmd.config.json tailored for docmd-search's web UI.
 *
 * Key architecture points:
 *  - docmd-search has ALREADY built the semantic index at this point
 *  - We tell docmd's plugin-search to use `semantic: true` with `indexDir`
 *    pointing at the pre-built index — plugin-search will skip re-indexing
 *  - docmd just serves the UI; no dependency loop back to docmd-search
 *  - Custom CSS applies the magenta docmd-search branding
 */
function generateDocmdConfig(rootDir: string, indexDir: string): string {
  const absRootDir = resolve(rootDir).replace(/\\/g, '/');
  const absIndexDir = resolve(indexDir).replace(/\\/g, '/');
  const absCssFile = resolve(indexDir, '_ui', 'custom.css').replace(/\\/g, '/');

  // JSON.stringify escapes quotes, backticks, and other metacharacters
  // that could break out of the template literal (CWE-94 defence).
  const safeSrc = JSON.stringify(absRootDir).slice(1, -1);
  const safeOut = JSON.stringify(absIndexDir + '/_site').slice(1, -1);
  const safeCss = JSON.stringify(absCssFile).slice(1, -1);
  const safeIdx = JSON.stringify(absIndexDir).slice(1, -1);

  return `// Auto-generated by docmd-search — do not edit manually.
// docmd-search has already built the semantic index; docmd just serves the UI.

export default {
  src: '${safeSrc}',
  out: '${safeOut}',
  title: 'docmd-search',
  description: 'Offline semantic search',

  theme: {
    customCss: ['${safeCss}'],
  },

  plugins: {
    // Semantic search with pre-built index — plugin-search skips indexing
    // and just reads from indexDir. No callback to docmd-search package.
    search: {
      semantic: true,
      showConfidence: true,
      indexDir: '${safeIdx}',
    },
  },

  // Disable features not needed for the search UI
  analytics: false,
  seo: false,
  sitemap: false,
};
`;
}

/**
 * Generate custom CSS for the docmd-search web UI.
 *
 * Overrides docmd's primary colour tokens with docmd-search's magenta palette.
 * Written to .docmd-search/_ui/custom.css and referenced via theme.customCss.
 */
function generateCustomCSS(): string {
  return `/* docmd-search — custom theme (magenta palette) */
/* Injected via theme.customCss when launching docmd --ui */

:root {
  /* Primary colour overrides — docmd reads these tokens */
  --color-primary:       #d946ef;
  --color-primary-hover: #c026d3;
  --color-primary-light: rgba(217, 70, 239, 0.12);
  --color-accent:        #e879f9;

  /* docmd-search brand colours (used in custom components below) */
  --ds-magenta:  #d946ef;
  --ds-purple:   #a855f7;
  --ds-gradient: linear-gradient(135deg, var(--ds-magenta), var(--ds-purple));
}

/* ── Badge ──────────────────────────────────────────────── */
/* Shown in the corner to identify the docmd-search UI */
.ds-badge {
  position: fixed;
  bottom: 16px;
  right: 16px;
  background: var(--ds-gradient);
  color: #fff;
  padding: 5px 11px;
  border-radius: 20px;
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.02em;
  opacity: 0.85;
  z-index: 9999;
  pointer-events: none;
  box-shadow: 0 2px 8px rgba(217, 70, 239, 0.3);
}

/* ── Search input focus ring ────────────────────────────── */
.docmd-search-input:focus,
#docmd-search-input:focus {
  border-color: var(--ds-magenta) !important;
  box-shadow: 0 0 0 3px rgba(217, 70, 239, 0.15) !important;
  outline: none;
}

/* ── Search result score badge ──────────────────────────── */
.search-score {
  background: var(--ds-gradient);
  color: #fff;
  padding: 2px 7px;
  border-radius: 10px;
  font-size: 10px;
  font-weight: 700;
  letter-spacing: 0.03em;
}

/* ── Indexing progress banner ───────────────────────────── */
.ds-indexing-banner {
  background: rgba(217, 70, 239, 0.08);
  border: 1px solid rgba(217, 70, 239, 0.2);
  border-radius: 8px;
  padding: 12px 16px;
  margin: 16px 0;
  font-size: 13px;
  display: flex;
  align-items: center;
  gap: 10px;
  color: var(--ds-magenta);
}

.ds-indexing-spinner {
  width: 14px;
  height: 14px;
  border: 2px solid rgba(217, 70, 239, 0.25);
  border-top-color: var(--ds-magenta);
  border-radius: 50%;
  animation: ds-spin 0.75s linear infinite;
  flex-shrink: 0;
}

@keyframes ds-spin {
  to { transform: rotate(360deg); }
}

/* ── Sidebar active link ────────────────────────────────── */
.sidebar-link.active,
.nav-link.active {
  color: var(--ds-magenta) !important;
  border-left-color: var(--ds-magenta) !important;
}
`;
}

/* ── Launch Function ───────────────────────────────────────── */

export interface LaunchOptions {
  /** Root directory being searched. */
  rootDir: string;
  /** Index output directory (.docmd-search). */
  indexDir: string;
  /** Port to run on (0 = auto). */
  port?: number;
  /** Open browser automatically. */
  open?: boolean;
  /** Verbose output. */
  verbose?: boolean;
}

/**
 * Launch the docmd web UI for docmd-search.
 *
 * Creates a staging area inside .docmd-search/ with:
 * - docmd.config.json (auto-generated)
 * - custom.css (magenta branding)
 *
 * Then spawns `npx @docmd/core dev` pointing at the target directory.
 */
export async function launchWebUI(options: LaunchOptions): Promise<{
  port: number;
  close: () => void;
}> {
  const { rootDir, indexDir, port = 0, open = true, verbose = false } = options;

  // ── Create staging area ──────────────────────────────

  const stagingDir = join(indexDir, '_ui');
  await mkdir(stagingDir, { recursive: true });

  // Write custom CSS first (config references its path)
  const cssContent = generateCustomCSS();
  await writeFile(join(stagingDir, 'custom.css'), cssContent, 'utf-8');

  // Write docmd config
  const configContent = generateDocmdConfig(rootDir, indexDir);
  await writeFile(join(stagingDir, 'docmd.config.json'), configContent, 'utf-8');

  // Copy navigation.json from index into rootDir so docmd picks it up
  // docmd reads navigation.json from the docs source directory automatically
  const indexNavFile = join(indexDir, 'navigation.json');
  const rootNavFile = join(rootDir, 'navigation.json');
  if (existsSync(indexNavFile) && !existsSync(rootNavFile)) {
    try {
      await copyFile(indexNavFile, rootNavFile);
      if (verbose) {
        console.log(`   ${A.dim}navigation → ${rootNavFile}${A.reset}`);
      }
    } catch {
      // Non-fatal — docmd will auto-generate navigation from files
    }
  }

  // Create index.md with docmd-search template if it doesn't exist
  // This ensures docmd has something to render even in non-markdown directories
  const indexMdPath = join(rootDir, 'index.md');
  if (!existsSync(indexMdPath)) {
    const indexMdContent = `---
title: docmd-search
template: docmd-search
---

# Search Results

Use the search bar above to find content in this directory.

Results will appear here as you type.
`;
    try {
      await writeFile(indexMdPath, indexMdContent, 'utf-8');
      if (verbose) {
        console.log(`   ${A.dim}index.md → ${indexMdPath}${A.reset}`);
      }
    } catch {
      // Non-fatal — docmd may still work with existing files
    }
  }

  if (verbose) {
    console.log(`   ${A.dim}staging → ${stagingDir}${A.reset}`);
  }

  // ── Spawn docmd ──────────────────────────────────────

  return new Promise((resolvePromise, reject) => {
    // Resolve the docmd binary:
    // 1. Local node_modules/.bin/docmd (from the rootDir or CWD)
    // 2. Globally installed docmd in PATH
    // 3. Fall back to: npx @docmd/core
    const resolvedBinary = resolveDocmdBinary(rootDir);
    let command: string;
    let args: string[];

    if (resolvedBinary) {
      command = resolvedBinary;
      args = ['dev', '--config', join(stagingDir, 'docmd.config.json')];
      if (verbose) {
        console.log(`   ${A.dim}using docmd at: ${resolvedBinary}${A.reset}`);
      }
    } else {
      // Fall back to npx
      command = 'npx';
      args = ['-y', '@docmd/core', 'dev', '--config', join(stagingDir, 'docmd.config.json')];
      if (verbose) {
        console.log(`   ${A.dim}falling back to: npx @docmd/core${A.reset}`);
      }
    }

    if (port > 0) {
      args.push('--port', String(port));
    }

    const child = spawn(command, args, {
      cwd: rootDir,
      stdio: ['ignore', 'pipe', 'pipe'],
      env: {
        ...process.env,
        DOCMD_SEARCH_INDEX: indexDir,
      },
    });

    let resolvedPort = port || 3000;
    let resolved = false;

    // Always parse stdout for port detection; optionally forward to terminal
    if (child.stdout) {
      child.stdout.on('data', (data: Buffer) => {
        const line = data.toString();
        if (verbose) process.stdout.write(line);

        // Detect port from docmd output
        const portMatch = line.match(/localhost:(\d+)/);
        if (portMatch && !resolved) {
          resolvedPort = parseInt(portMatch[1], 10);
          resolved = true;

          console.log(`   ${A.magenta}◆${A.reset} Web UI ready`);
          console.log(`   ${A.dim}http://localhost:${resolvedPort}${A.reset}`);
          console.log('');

          // Open browser
          if (open) {
            openBrowser(`http://localhost:${resolvedPort}`);
          }

          resolvePromise({
            port: resolvedPort,
            close: () => {
              child.kill('SIGTERM');
            },
          });
        }
      });
    }

    if (child.stderr && verbose) {
      child.stderr.on('data', (data: Buffer) => process.stderr.write(data));
    }

    // Handle errors
    child.on('error', (err) => {
      if (err.message.includes('ENOENT') || err.message.includes('npx')) {
        console.log('');
        console.log(`   ${A.red}✗${A.reset} Could not launch web UI`);
        console.log('');
        console.log(`   ${A.dim}Web UI requires @docmd/core. Install it with:${A.reset}`);
        console.log(`     npm install -g @docmd/core`);
        console.log('');
        console.log(`   ${A.dim}Or use the TUI search: docmd-search ./docs (without --ui)${A.reset}`);
        console.log('');
      }
      reject(err);
    });

    child.on('exit', (code) => {
      if (!resolved) {
        if (code !== 0) {
          console.log('');
          console.log(`   ${A.red}✗${A.reset} docmd exited with code ${code}`);
          console.log('');
          console.log(`   ${A.dim}Web UI requires @docmd/core. Install it with:${A.reset}`);
          console.log(`     npm install -g @docmd/core`);
          console.log('');
          console.log(`   ${A.dim}Or use the TUI search: docmd-search ./docs (without --ui)${A.reset}`);
          console.log('');
        }
        reject(new Error(`docmd exited with code ${code}`));
      }
    });

    // Timeout: if docmd doesn't start in 30s, fallback
    setTimeout(() => {
      if (!resolved) {
        resolved = true;
        resolvePromise({
          port: resolvedPort,
          close: () => {
            child.kill('SIGTERM');
          },
        });
      }
    }, 30000);
  });
}

/* ── Browser Opener ────────────────────────────────────────── */

function openBrowser(url: string): void {
  try {
    const cmd = process.platform === 'darwin' ? 'open'
      : process.platform === 'win32' ? 'start'
      : 'xdg-open';
    spawn(cmd, [url], { detached: true, stdio: 'ignore' }).unref();
  } catch {
    // Silently fail — user can open manually
  }
}

/* ── Binary Resolver ───────────────────────────────────────── */

/**
 * Resolve the docmd CLI binary.
 *
 * Priority:
 *  1. Local node_modules/.bin/docmd (rootDir or CWD)
 *  2. docmd in PATH (global install)
 *  3. Returns null → caller falls back to npx
 */
function resolveDocmdBinary(rootDir: string): string | null {
  const absRootDir = resolve(rootDir);

  // Walk up from rootDir and CWD looking for node_modules/.bin/docmd
  const searchRoots = [absRootDir, resolve(process.cwd())];
  const visited = new Set<string>();

  for (const start of searchRoots) {
    let dir = start;
    while (true) {
      if (visited.has(dir)) break;
      visited.add(dir);

      const candidate = join(dir, 'node_modules', '.bin', 'docmd');
      if (existsSync(candidate)) return candidate;

      const parent = join(dir, '..');
      if (parent === dir) break; // filesystem root
      dir = parent;
    }
  }

  // Check global PATH — use execFileSync (no shell) for safety.
  try {
    const whichCmd = process.platform === 'win32' ? 'where' : 'which';
    const result = execFileSync(whichCmd, ['docmd'], { stdio: 'pipe' })
      .toString()
      .trim()
      .split('\n')[0]
      .trim();
    if (result && existsSync(result)) return result;
  } catch {
    // Not in PATH
  }

  return null;
}