/**
 * --------------------------------------------------------------------
 * docmd-search : offline semantic search for docs, zero-config.
 *
 * @package     docmd-search (and ecosystem)
 * @website     https://docmd.io/search
 * @repository  https://github.com/docmd-io/docmd-search
 * @license     MIT
 * @copyright   Copyright (c) 2026-present docmd.io
 *
 * [docmd-source] - Please do not remove this header.
 * --------------------------------------------------------------------
 */

/**
 * Web UI launcher via docmd.
 *
 * Spawns `npx @docmd/core dev` with a pre-built config that:
 * - Points at the target directory
 * - Enables semantic-search plugin
 * - Uses navigation.json from .docmd-search/ for instant nav
 * - Custom CSS (magenta branding)
 * - Disables unnecessary features (analytics, seo, sitemap)
 *
 * docmd-search does NOT depend on docmd — it spawns it via npx.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { spawn } from 'node:child_process';

/* ── ANSI ──────────────────────────────────────────────────── */

const A = {
  reset: '\x1b[0m',
  bold:  '\x1b[1m',
  dim:   '\x1b[2m',
  magenta: '\x1b[35m',
  green: '\x1b[32m',
  red:   '\x1b[31m',
  yellow:'\x1b[33m',
};

/* ── Config Generation ─────────────────────────────────────── */

/**
 * Generate a docmd.config.js tailored for docmd-search's web UI.
 */
function generateDocmdConfig(rootDir: string, indexDir: string): string {
  const absRootDir = resolve(rootDir).replace(/\\/g, '/');
  const absIndexDir = resolve(indexDir).replace(/\\/g, '/');

  return `// Auto-generated by docmd-search — do not edit manually.
// This config is used to launch docmd as a web UI for semantic search.

export default {
  docsDir: '${absRootDir}',
  outDir: '.docmd-search/_site',

  site: {
    title: 'docmd-search',
    description: 'Offline semantic search',
  },

  // Disable features we don't need for the search UI
  search: false,  // semantic-search plugin replaces this
  analytics: false,
  seo: false,
  sitemap: false,

  // Custom theme: magenta branding for docmd-search
  head: [
    '<style>',
    '  :root {',
    '    --color-primary: #d946ef;',
    '    --color-primary-hover: #c026d3;',
    '    --color-accent: #e879f9;',
    '  }',
    '  .docmd-search-badge {',
    '    position: fixed;',
    '    bottom: 16px;',
    '    right: 16px;',
    '    background: linear-gradient(135deg, #d946ef, #a855f7);',
    '    color: white;',
    '    padding: 6px 12px;',
    '    border-radius: 20px;',
    '    font-size: 12px;',
    '    font-weight: 600;',
    '    opacity: 0.8;',
    '    z-index: 9999;',
    '    pointer-events: none;',
    '  }',
    '</style>',
  ],

  body: [
    '<div class="docmd-search-badge">⚡ docmd-search</div>',
  ],

  // Plugin configuration — semantic-search reads from .docmd-search/
  plugins: {
    'semantic-search': {
      indexDir: '${absIndexDir}',
    },
  },
};
`;
}

/**
 * Generate custom CSS for the docmd-search web UI.
 */
function generateCustomCSS(): string {
  return `/* docmd-search custom styles */
:root {
  --ds-magenta: #d946ef;
  --ds-purple: #a855f7;
  --ds-gradient: linear-gradient(135deg, var(--ds-magenta), var(--ds-purple));
}

/* Search input highlight */
.search-input:focus {
  border-color: var(--ds-magenta) !important;
  box-shadow: 0 0 0 3px rgba(217, 70, 239, 0.15) !important;
}

/* Search result score badge */
.search-score {
  background: var(--ds-gradient);
  color: white;
  padding: 2px 8px;
  border-radius: 12px;
  font-size: 11px;
  font-weight: 600;
}

/* Indexing progress indicator */
.ds-indexing-banner {
  background: rgba(217, 70, 239, 0.1);
  border: 1px solid rgba(217, 70, 239, 0.2);
  border-radius: 8px;
  padding: 12px 16px;
  margin: 16px 0;
  font-size: 14px;
  display: flex;
  align-items: center;
  gap: 8px;
}

.ds-indexing-spinner {
  width: 16px;
  height: 16px;
  border: 2px solid rgba(217, 70, 239, 0.3);
  border-top-color: var(--ds-magenta);
  border-radius: 50%;
  animation: ds-spin 0.8s linear infinite;
}

@keyframes ds-spin {
  to { transform: rotate(360deg); }
}
`;
}

/* ── Launch Function ───────────────────────────────────────── */

export interface LaunchOptions {
  /** Root directory being searched. */
  rootDir: string;
  /** Index output directory (.docmd-search). */
  indexDir: string;
  /** Port to run on (0 = auto). */
  port?: number;
  /** Open browser automatically. */
  open?: boolean;
  /** Verbose output. */
  verbose?: boolean;
}

/**
 * Launch the docmd web UI for docmd-search.
 *
 * Creates a staging area inside .docmd-search/ with:
 * - docmd.config.js (auto-generated)
 * - custom.css (magenta branding)
 *
 * Then spawns `npx @docmd/core dev` pointing at the target directory.
 */
export async function launchWebUI(options: LaunchOptions): Promise<{
  port: number;
  close: () => void;
}> {
  const { rootDir, indexDir, port = 0, open = true, verbose = false } = options;

  // ── Create staging area ──────────────────────────────

  const stagingDir = join(indexDir, '_ui');
  await mkdir(stagingDir, { recursive: true });

  // Write config
  const configContent = generateDocmdConfig(rootDir, indexDir);
  await writeFile(join(stagingDir, 'docmd.config.js'), configContent, 'utf-8');

  // Write custom CSS
  const cssContent = generateCustomCSS();
  await writeFile(join(stagingDir, 'custom.css'), cssContent, 'utf-8');

  if (verbose) {
    console.log(`   ${A.dim}staging → ${stagingDir}${A.reset}`);
  }

  // ── Spawn docmd ──────────────────────────────────────

  return new Promise((resolvePromise, reject) => {
    const args = [
      '-y', '@docmd/core',
      'dev',
      '--config', join(stagingDir, 'docmd.config.js'),
    ];

    if (port > 0) {
      args.push('--port', String(port));
    }

    const child = spawn('npx', args, {
      cwd: rootDir,
      stdio: verbose ? 'inherit' : 'pipe',
      env: {
        ...process.env,
        DOCMD_SEARCH_INDEX: indexDir,
      },
    });

    let resolvedPort = port || 3000;
    let resolved = false;

    // Parse stdout for port detection
    if (!verbose && child.stdout) {
      child.stdout.on('data', (data: Buffer) => {
        const line = data.toString();

        // Detect port from docmd output
        const portMatch = line.match(/localhost:(\d+)/);
        if (portMatch && !resolved) {
          resolvedPort = parseInt(portMatch[1], 10);
          resolved = true;

          console.log(`   ${A.magenta}◆${A.reset} Web UI ready`);
          console.log(`   ${A.dim}http://localhost:${resolvedPort}${A.reset}`);
          console.log('');

          // Open browser
          if (open) {
            openBrowser(`http://localhost:${resolvedPort}`);
          }

          resolvePromise({
            port: resolvedPort,
            close: () => {
              child.kill('SIGTERM');
            },
          });
        }
      });
    }

    // Handle errors
    child.on('error', (err) => {
      if (err.message.includes('ENOENT') || err.message.includes('npx')) {
        console.log('');
        console.log(`   ${A.red}✗${A.reset} Could not launch web UI`);
        console.log('');
        console.log(`   ${A.dim}Web UI requires @docmd/core. Install it with:${A.reset}`);
        console.log(`     npm install -g @docmd/core`);
        console.log('');
        console.log(`   ${A.dim}Or use the TUI search: docmd-search ./docs (without --ui)${A.reset}`);
        console.log('');
      }
      reject(err);
    });

    child.on('exit', (code) => {
      if (!resolved) {
        if (code !== 0) {
          console.log('');
          console.log(`   ${A.red}✗${A.reset} docmd exited with code ${code}`);
          console.log('');
          console.log(`   ${A.dim}Web UI requires @docmd/core. Install it with:${A.reset}`);
          console.log(`     npm install -g @docmd/core`);
          console.log('');
          console.log(`   ${A.dim}Or use the TUI search: docmd-search ./docs (without --ui)${A.reset}`);
          console.log('');
        }
        reject(new Error(`docmd exited with code ${code}`));
      }
    });

    // Timeout: if docmd doesn't start in 30s, fallback
    setTimeout(() => {
      if (!resolved) {
        resolved = true;
        resolvePromise({
          port: resolvedPort,
          close: () => {
            child.kill('SIGTERM');
          },
        });
      }
    }, 30000);
  });
}

/* ── Browser Opener ────────────────────────────────────────── */

function openBrowser(url: string): void {
  try {
    const cmd = process.platform === 'darwin' ? 'open'
      : process.platform === 'win32' ? 'start'
      : 'xdg-open';
    spawn(cmd, [url], { detached: true, stdio: 'ignore' }).unref();
  } catch {
    // Silently fail — user can open manually
  }
}
